name: bolsify
description: "A new Flutter project for management of personal finance"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_riverpod: ^2.6.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/styles/

  # Configuración mínima y oficial de localización


  #fonts:
  # Para agregar fuentes personalizadas, usa el siguiente formato:
  # - family: Inter
  #   fonts:
  #     - asset: assets/fonts/Inter-Regular.ttf
  #     - asset: assets/fonts/Inter-Bold.ttf
  #       weight: 700

